config/routes.rb
Rails.application.routes.draw do
  resources :list_items do 
  	member do
  		get :soft_delete
      get :restore
  	end
  end

  resources :lists do
  	member do
  		get :soft_delete
      get :restore
  	end
  end

  get 'trash_lists', to: 'lists#trash_lists'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	include Deletion

	has_many :list_items, dependent: :destroy

	validates :name, presence: true
	validates :description, presence: true


end

app/models/list_item.rb
class ListItem < ApplicationRecord
  include Deletion

  belongs_to :list

  validates :name, presence: true
  validates :description, presence: true

  scope :active, -> { where("active=?", true)}
  scope :in_active, -> { where("active=?", false)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy, :soft_delete, :restore]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new(list_id: params[:list_id])
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to lists_path, notice: 'List item was successfully created.' }
        format.json { render :show, status: :created, location: @list_item }
      else
        format.html { render :new }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to lists_path, notice: 'List item was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to lists_path, notice: 'List item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def soft_delete
    @list_item.soft_delete
    respond_to do |format|
      format.html { redirect_to lists_path, notice: 'List was soft deleted.' }
      format.json { head :no_content }
    end
  end

  def restore
    @list_item.restore
    respond_to do |format|
      format.html { redirect_to trash_lists_path, notice: 'List item has been restored.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:list_id, :name, :description, :active)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :soft_delete, :restore]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all.where(active: true)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def soft_delete
    @list.soft_delete
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was soft deleted.' }
      format.json { head :no_content }
    end
  end

  def restore
    @list.restore
    respond_to do |format|
      format.html { redirect_to trash_lists_path, notice: 'List has been restored.' }
      format.json { head :no_content }
    end
  end

  def trash_lists
    @lists = List.all.where(active: false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Umai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_items/_form.html.erb
<%= form_for(list_item) do |f| %>
  <% if list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style= "display:none">
    <%= f.label :list_id %>
    <%= f.text_field :list_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Back', lists_path %>

app/views/list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Items</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Description</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= list_item.list %></td>
        <td><%= list_item.name %></td>
        <td><%= list_item.description %></td>
        
        <td><%= link_to 'Show', list_item %></td>
        <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List Item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Back', lists_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @list_item.list %>
</p>

<p>
  <strong>Name:</strong>
  <%= @list_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list_item.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @list_item.active %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<table id="lists">
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    
    
    <% @lists.each_with_index do |list, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= list.name %></td>
        <td><%= list.description %></td>
        
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Soft Delete', soft_delete_list_path(list), data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Hard Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% if list.list_items.active.present? %>
        <tr>
          <td></td>
          <td colspan="5" style="font-size:15px;font-weight: bold;background-color: #4CAF50;">List Items</td>
        </tr>
      <% end %>
      <% list.list_items.active.each do |list_item|%>
        
        <tr>
          <td></td>
          <td><%= list_item.name %></td>
          <td><%= list_item.description %></td>
          <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
          <td><%= link_to 'Soft Delete', soft_delete_list_item_path(list_item), data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Hard Delete', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
         <td colspan="5"><%= link_to 'Create New List Item', new_list_item_path(list_id: list.id) %></td>
      <tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New List', new_list_path %>
<br/>
<%= link_to 'Trash List', trash_lists_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @list.active %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/trash_lists.html.erb
<p id="notice"><%= notice %></p>

<table id="lists">
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    
    
    <% @lists.each_with_index do |list, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= list.name %></td>
        <td><%= list.description %></td>
        
        <td><%= link_to 'Restore', restore_list_path(list) %></td>
        <td><%= link_to 'Hard Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
      <% if list.list_items.in_active.present? %>
        <tr>
          <td></td>
          <td colspan="5" style="font-size:15px;font-weight: bold;background-color: #4CAF50;">List Items</td>
        </tr>
      <% end %>
      <% list.list_items.in_active.each do |list_item|%>
        
        <tr>
          <td></td>
          <td><%= list_item.name %></td>
          <td><%= list_item.description %></td>
          <td><%= link_to 'Restore', restore_list_item_path(list) %></td>
          <td><%= link_to 'Hard Delete', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Lists', lists_path %>